ALTER TABLE Keg 
ADD CONSTRAINT Keg_BatchID_FK FOREIGN KEY (BatchID) REFERENCES Batch (BatchID);

ALTER TABLE Batch 
ADD CONSTRAINT Batch_BeerID_FK FOREIGN KEY (BeerID) REFERENCES Beer (BeerID);

ALTER TABLE Batch 
ADD CONSTRAINT Batch_BatchStatusID_FK OREIGN KEY (BatchStatusID) REFERENCES BatchStatus (BatchStatusID);