name: Setup workflow
on:
  workflow_call:
    secrets:
        AWS_ASSUME_ROLE:
            required: true
        AWS_REGION:
            required: true
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Assume the deploy pipeline user role
              uses: aws-actions/configure-aws-credentials@v4.0.1
              with:
                role-to-assume: ${{secrets.AWS_ASSUME_ROLE}}
                role-session-name: GitHub_to_AWS_via_FederatedOIDC
                aws-region: ${{secrets.AWS_REGION }}

    