name: Terraform Plan

on:
  workflow_call:
    secrets:
        AWS_ASSUME_ROLE:
            required: true
        AWS_REGION:
            required: true

jobs:
  checkout_and_credentials_setup:
    uses: ./.github/workflows/_setup_workflow.yml@main
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
  terraform_setup:
    runs-on: ubuntu-latest
    needs: checkout_and_credentials_setup
    steps:
      - name: Terraform Init
        id: init
        run: |
          cd terraform
          make tf_init

      - name: Terraform Validate
        id: validate
        run: |
          echo "## Terraform Validate" >> $GITHUB_STEP_SUMMARY
          make tf_validate >> $GITHUB_STEP_SUMMARY

      - name: Terraform Plan
        id: plan
        run: |
          echo "## Terraform Plan" >> $GITHUB_STEP_SUMMARY
          make tf_plan >> $GITHUB_STEP_SUMMARY
