name: Development Database CI/CD

on:
  push:
    branches: [ dev ]

permissions:
  contents: read

jobs:
  # ci-workflow:
  #   uses: ./.github/workflows/dev-db-ci.yml
  #   secrets: inherit

  migrate_db:
    name: Migrate Dev DB
    # needs: ci-workflow
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Liquibase
        run: |
          curl -L https://github.com/liquibase/liquibase/releases/download/v${LB_VERSION}/liquibase-${LB_VERSION}.zip --output liquibase.zip
          unzip -o -d liquibase liquibase.zip
        env:
          LB_VERSION: ${{ vars.LIQUIBASE_VERSION }}

      # CREATE LIQUIBASE PROPERTIES

      - name: Migrate Database to RDS
        run: ./liquibase/liquibase update
        