name: Fetch liquibase config file from S3

on:
    workflow_call:
        inputs:
            DB_INSTANCE_NAME:
                type: string
                description: 'DB Instance Name'
                required: true
                default: 'craft-beer-db'
            AWS_ASSUME_ROLE:
                type: string
                description: 'AWS Assume Role'
                required: true
            AWS_REGION: 
                type: string
                description: 'AWS Region'
                required: true
                default: 'eu-west-1'
            LIQUIBASE_CONFIG_BUCKET:
                type: string
                description: 'Liquibase Config Bucket'
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout-repository
          uses: actions/checkout@v4
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ inputs.AWS_ASSUME_ROLE }}
            aws-region: ${{ inputs.AWS_REGION }}
        - name: Fetch AWS RDS Enpoint address
          run: |
                echo "Fetching Liquibase .env from S3"
                aws s3api get-object --bucket ${{inputs.LIQUIBASE_CONFIG_BUCKET}} --key .env .env