name: Development Database CI/CD

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  # ci-workflow:
  #   uses: ./.github/workflows/db-ci.yml
  #   secrets: inherit

  migrate_db:
    name: Migrate Dev DB
    # needs: ci-workflow
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Liquibase
        run: |
          curl -L https://github.com/liquibase/liquibase/releases/download/v${LB_VERSION}/liquibase-${LB_VERSION}.zip --output liquibase.zip
          unzip -o -d liquibase liquibase.zip
        env:
          LB_VERSION: 4.25.1

      - name: Retrieve Liquibase Config
        run: aws s3 cp ${{ secrets.BUCKET_OBJ_URL }} liquibase.properties

      - name: Migrate Database to RDS
        run: ./liquibase/liquibase update
        