name: Dev Terraform Apply
on:

  push:
    branches:
      - dev


env:
  WORKING_DIRECTORY: ./terraform


permissions:
  contents: read
  id-token: write
jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Assume the deploy pipeline user role
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE}}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{secrets.AWS_REGION }}
      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIRECTORY }}
        id: init
        run: |
          make tf_init

      - name: Terraform Validate
        working-directory: ${{ env.WORKING_DIRECTORY }}
        id: validate
        run: |
          echo "## Terraform Validate" >> $GITHUB_STEP_SUMMARY
          make tf_validate >> $GITHUB_STEP_SUMMARY

      - name: Terraform Plan
        working-directory: ${{ env.WORKING_DIRECTORY }}
        id: plan
        run: |
          echo "## Terraform Plan" >> $GITHUB_STEP_SUMMARY
          make tf_plan >> $GITHUB_STEP_SUMMARY
  TerraformApply:
    runs-on: ubuntu-latest
    needs: terraform_plan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Assume the deploy pipeline user role
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE}}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{secrets.AWS_REGION }}
          role-chaining: true
      - name: Terraform Apply
        working-directory: ${{ env.WORKING_DIRECTORY }}
        id: apply
        run: |
          echo "## Terraform Apply" >> $GITHUB_STEP_SUMMARY
          cd terraform
          make tf_apply >> $GITHUB_STEP_SUMMARY