name: Terraform Plan
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  TerraformPlan:
    runs-on: ubuntu-latest
    needs:
      - AssumeRoleAndCallIdentity
    steps:
      - name: Terraform Init
        id: init
        run: |
          cd terraform
          make tf_init

      - name: Terraform Validate
        id: validate
        run: |
          echo "## Terraform Validate" >> $GITHUB_STEP_SUMMARY
          make tf_validate >> $GITHUB_STEP_SUMMARY

      - name: Terraform Plan
        id: plan
        run: |
          echo "## Terraform Plan" >> $GITHUB_STEP_SUMMARY
          make tf_plan >> $GITHUB_STEP_SUMMARY
