name: Prod Terraform Apply
on:
  push:
    branches:
      - main

jobs:
  TerraformApply:
    runs-on: ubuntu-latest
    needs:
      - AssumeRoleAndCallIdentity
      - TerraformPlan
    steps:
      - name: Terraform Apply
        id: apply
        run: |
          echo "## Terraform Apply" >> $GITHUB_STEP_SUMMARY
          cd terraform
          make tf_apply >> $GITHUB_STEP_SUMMARY
