name: Terraform Plan

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  terraform_plan:
    uses: .github/workflows/_terraform_plan_workflow.yml@main
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

