name: Prod Terraform Apply
on:
  push:
    branches:
      - main

jobs:
  TerraformApply:
    runs-on: ubuntu-latest
    needs:
      - AssumeRoleAndCallIdentity
      - TerraformPlan
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Assume the deploy pipeline user role
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE}}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{secrets.AWS_REGION }}
      - name: Terraform Apply
        id: apply
        run: |
          echo "## Terraform Apply" >> $GITHUB_STEP_SUMMARY
          cd terraform
          make tf_apply >> $GITHUB_STEP_SUMMARY
