name: Terraform Plan

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  TerraformPlan:
    runs-on: ubuntu-latest
    needs:
      - AssumeRoleAndCallIdentity
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Assume the deploy pipeline user role
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE}}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{secrets.AWS_REGION }}

      - name: Terraform Init
        id: init
        run: |
          cd terraform
          make tf_init

      - name: Terraform Validate
        id: validate
        run: |
          echo "## Terraform Validate" >> $GITHUB_STEP_SUMMARY
          make tf_validate >> $GITHUB_STEP_SUMMARY

      - name: Terraform Plan
        id: plan
        run: |
          echo "## Terraform Plan" >> $GITHUB_STEP_SUMMARY
          make tf_plan >> $GITHUB_STEP_SUMMARY
