name: Dev Terraform Apply
on:
  push:
    branches:
      - dev

jobs:
  terraform_plan:
    uses: ./.github/workflows/_terraform_plan_workflow.yml@main
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
  TerraformApply:
    runs-on: ubuntu-latest
    needs:
      - terraform_plan
      
    steps:
      - name: Terraform Apply
        id: apply
        run: |
          echo "## Terraform Apply" >> $GITHUB_STEP_SUMMARY
          cd terraform
          make tf_apply >> $GITHUB_STEP_SUMMARY
